name: Spider666

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Jar
      run: |  
           #删除垃圾爬虫
           echo "123"
           echo $ANDROID_HOME
           echo "234"


         
