name: Spider

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Delete workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0 
        #The number of days that is used to compare with the retention days of each workflow.
        keep_minimum_runs: 2 
        #The minimum runs to keep for each workflow.
        
    - name: Clone project
      run: |
        rm -rf jar/custom_spider.jar
        git clone --recurse-submodules https://github.com/lushunming/AndroidCatVodSpider project
        sed -i 's/mirrors.cloud.tencent.com\gradle/services.gradle.org\/distributions/g' project/gradle/wrapper/gradle-wrapper.properties        
      
    - name: Customize Spider
      working-directory: ./project
      run: |  
         #删除垃圾爬虫
         #rm -rf app/src/main/java/com/github/catvod/spider/Ali.java
         rm -rf app/src/main/java/com/github/catvod/spider/Dm84.java
         rm -rf app/src/main/java/com/github/catvod/spider/Doll.java
         rm -rf app/src/main/java/com/github/catvod/spider/Eighteen.java
         rm -rf app/src/main/java/com/github/catvod/spider/Hanime.java
         rm -rf app/src/main/java/com/github/catvod/spider/JSDemo.java
         rm -rf app/src/main/java/com/github/catvod/spider/Jable.java
         rm -rf app/src/main/java/com/github/catvod/spider/Jianpian.java
         rm -rf app/src/main/java/com/github/catvod/spider/Kanqiu.java
         rm -rf app/src/main/java/com/github/catvod/spider/Miss.java
         rm -rf app/src/main/java/com/github/catvod/spider/Notice.java                  
         rm -rf app/src/main/java/com/github/catvod/spider/PanSearch.java
         rm -rf app/src/main/java/com/github/catvod/spider/PanSou.java
         rm -rf app/src/main/java/com/github/catvod/spider/Star.java
         rm -rf app/src/main/java/com/github/catvod/spider/UpYun.java
         #rm -rf app/src/main/java/com/github/catvod/spider/Wogg.java
         rm -rf app/src/main/java/com/github/catvod/spider/XiaoZhiTiao.java
         rm -rf app/src/main/java/com/github/catvod/spider/YiSo.java
         rm -rf app/src/main/java/com/github/catvod/spider/Ysj.java
         rm -rf app/src/main/java/com/github/catvod/spider/Zhaozy.java

         #删除阿里云盘
         #rm -rf app/src/main/java/com/github/catvod/api
         #rm -rf app/src/main/java/com/github/catvod/bean/ali
         #rm -rf app/src/main/java/com/github/catvod/bean/upyun

         #sed -i "22,31d" app/src/main/java/com/github/catvod/spider/Push.java
         #sed -i "/ali.player/c return null;" app/src/main/java/com/github/catvod/spider/Push.java
         #sed -i "/ali.detail/d" app/src/main/java/com/github/catvod/spider/Push.java
         #sed -i "/\"ali\"/d;/return Ali/d" app/src/main/java/com/github/catvod/spider/Proxy.java
         
         #删除Doll残留
         sed -i "/Doll/d" app/src/main/java/com/github/catvod/debug/MainActivity.java

    - name: Build the Jar
      working-directory: ./project
      run: |  
         #删除垃圾爬虫
         echo "123"
         echo $ANDROID_HOME
         echo "234"
         
